server:
  port: 9296
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/suniljeevan/Presi-HRMS
          clone-on-start: true